version: '3.8'
services:
  eureka-server:
    image: tarassov12346/eureka-microservice:latest
    container_name: eureka-server
    network_mode: host
    restart: always
  gateway-service:
    image: tarassov12346/gateway-service:latest
    container_name: gateway-service
    network_mode: host
    environment:
    - SERVER_PORT=5555  # <-- ДОБАВЬТЕ ЭТУ СТРОКУ СЮДА
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:1111/eureka/
    - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    - JAVA_TOOL_OPTIONS=-Xmx256m
    - EUREKA_CLIENT_FETCH_REGISTRY=true
    - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
    - EUREKA_CLIENT_INITIALIZE_ON_DEMAND=false
    depends_on:
    - eureka-server
  
  users-service:
    image: tarassov12346/users-service:latest
    container_name: users-service
    network_mode: host
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:1111/eureka/
    - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    - JAVA_TOOL_OPTIONS="-Xmx256m"
    depends_on:
    - eureka-server
  mongo-service:
    image: tarassov12346/mongo-service:latest
    container_name: mongo-service
    network_mode: host
    environment:
    - SPRING_DATA_MONGODB_URI=mongodb://localhost:27017/game
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:1111/eureka/
    - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    - JAVA_TOOL_OPTIONS="-Xmx256m"
    depends_on:
    - eureka-server
  game-service:
    image: tarassov12346/game-service:latest
    container_name: game-service
    network_mode: host
    environment:
    - SERVER_PORT=2223
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:1111/eureka/
    - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    - JAVA_TOOL_OPTIONS="-Xmx256m"
    depends_on:
    - eureka-server
  tetris-game:
    image: tarassov12346/raging-horse-tetris:latest
    container_name: tetris-game
    network_mode: host
    environment:
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:1111/eureka/
    - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    - JAVA_TOOL_OPTIONS="-Xmx256m"
    depends_on:
    - eureka-server
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    network_mode: host
    environment:
    - POSTGRES_DB=game
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=mine
    restart: always
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    network_mode: host
    restart: always
