version: '3.8'

services:
  # 1. СЕРВЕР РЕГИСТРАЦИИ (ПОРТ: 1111)
  eureka-server:
    image: tarassov12346/eureka-microservice:latest
    container_name: eureka-server
    network_mode: host
    restart: always

  # 2. СЕТЕВОЙ ШЛЮЗ (ПОРТ: 5555)
  gateway-service:
    image: tarassov12346/gateway-service:latest
    container_name: gateway-service
    network_mode: host
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:1111/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - JAVA_TOOL_OPTIONS=-Xmx256m
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_INITIALIZE_ON_DEMAND=false
    depends_on:
      - eureka-server

  # 3. СЕРВИС ПОЛЬЗОВАТЕЛЕЙ (ПОРТ: 4444)
  users-service:
    image: tarassov12346/users-service:latest
    container_name: users-service
    network_mode: host
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:1111/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - JAVA_TOOL_OPTIONS="-Xmx256m"
    depends_on:
      - eureka-server

  # 4. СЕРВИС КАРТИНОК MONGO (ПОРТ: 3333)
  mongo-service:
    image: tarassov12346/mongo-service:latest
    container_name: mongo-service
    network_mode: host
    environment:
      # Исправлено: направляем строго на localhost хост-сети
      - SPRING_DATA_MONGODB_URI=mongodb://localhost:27017/game
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:1111/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - JAVA_TOOL_OPTIONS="-Xmx256m"
    depends_on:
      - eureka-server

  # 5. ИГРОВОЙ ДВИЖОК (ПОРТ: 2223)
  game-service:
    image: tarassov12346/game-service:latest
    container_name: game-service
    network_mode: host
    environment:
      # Исправлено: уходим с занятого гитхабом порта 2222 на свободный 2223
      - SERVER_PORT=2223
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:1111/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - JAVA_TOOL_OPTIONS="-Xmx256m"
    depends_on:
      - eureka-server

  # 6. ФРОНТЕНД И ВЕБСОКЕТЫ ТЕТРИСА
  tetris-game:
    # Исправлено: точное имя репозитория из вашего Docker Hub
    image: tarassov12346/raging-horse-tetris:latest
    container_name: tetris-game
    network_mode: host
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:1111/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - JAVA_TOOL_OPTIONS="-Xmx256m"
    depends_on:
      - eureka-server

  # === БАЗЫ ДАННЫХ ===
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    network_mode: host
    environment:
      # Настройки строго под ваш users-service
      - POSTGRES_DB=game
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mine
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    network_mode: host
    restart: always
